=== abbas-siddiqui/Template_Based_Composition/XML/Descriptions/Template_Description.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 rel. 2 (x64) (http://www.altova.com) by Markus Hillenbrand (University of Kaiserslautern) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Template">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="QoS_Parameters" minOccurs="0">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="QoS">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Effect" type="xs:token"/>
										<xs:element name="Operator">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="="/>
													<xs:enumeration value="=&gt;"/>
													<xs:enumeration value="&lt;"/>
													<xs:enumeration value="=&lt;"/>
													<xs:enumeration value="&gt;"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Attribute">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:token">
														<xs:attribute name="Unit" type="xs:string" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Domains">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="Domain">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:token">
											<xs:attribute name="Name"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Placeholders">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="PlaceHolder">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ToggleEnable">
											<xs:complexType>
												<xs:attribute name="isToggle" type="xs:boolean" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="Port" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence maxOccurs="unbounded">
													<xs:element name="OfferedEffect">
														<xs:complexType>
															<xs:attribute name="Effect" type="xs:token" use="required"/>
															<xs:attribute name="Operator" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:token">
																		<xs:enumeration value="=&gt;"/>
																		<xs:enumeration value="=&lt;"/>
																		<xs:enumeration value="&lt;"/>
																		<xs:enumeration value="&gt;"/>
																		<xs:enumeration value="="/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="Attribute" type="xs:token" use="required"/>
														</xs:complexType>
													</xs:element>
													<xs:element name="RequiredEffect" minOccurs="0">
														<xs:complexType>
															<xs:attribute name="Effect" type="xs:token" use="required"/>
															<xs:attribute name="Operator" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:token">
																		<xs:enumeration value="=&gt;"/>
																		<xs:enumeration value="=&lt;"/>
																		<xs:enumeration value="&lt;"/>
																		<xs:enumeration value="&gt;"/>
																		<xs:enumeration value="="/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="Attribute" type="xs:token" use="required"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="PortID" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="PreSelection" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="SuggestedBB">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="BB">
																	<xs:complexType>
																		<xs:attribute name="ID" use="required"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="PreSelectedBBs">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="BB" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="ID" use="required"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="Name" use="required"/>
									<xs:attribute name="ID" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Connections">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="Connection">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Port" maxOccurs="2">
											<xs:complexType>
												<xs:attribute name="PortID" type="xs:string" use="required"/>
												<xs:attribute name="Placeholder" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CoveredEffects">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="CoveredEffect">
								<xs:complexType>
									<xs:attribute name="Effect" type="xs:token" use="required"/>
									<xs:attribute name="Operator" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="=&gt;"/>
												<xs:enumeration value="=&lt;"/>
												<xs:enumeration value="&lt;"/>
												<xs:enumeration value="&gt;"/>
												<xs:enumeration value="="/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="Attribute" type="xs:token"/>
									<xs:attribute name="isToggle"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Name"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== abbas-siddiqui/Template_Based_Composition/XML/TemplatesPool/ImageTransmission3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file://SHADOW/siddiqui/Project_Work/Berlin_Status_Meeting_2012/TemplateBasedApproach/Prototyp_Implemenation/Template_Demo/Extra_Files/Descriptions/Template_Description.xsd">
		<Domains>
		<Domain>ImageTransmission</Domain>
	</Domains>
	<Placeholders>
		<PlaceHolder Name="app" ID="3">
			<ToggleEnable isToggle="false"></ToggleEnable>
			<Port PortID="6">
				<OfferedEffect Effect="application" Operator="=" Attribute="true"/>
			</Port>
		</PlaceHolder>
		<PlaceHolder Name="Compression" ID="2">
			<ToggleEnable isToggle="false"></ToggleEnable>
			<Port PortID="9">
				<OfferedEffect Effect="Data" Operator="=" Attribute="true"></OfferedEffect>
			</Port>
			<Port PortID="2">
				<OfferedEffect Effect="DataReduction" Operator="=" Attribute="true"></OfferedEffect>
			</Port>
		</PlaceHolder>
		<PlaceHolder Name="Encryption" ID="5">
			<ToggleEnable isToggle="false"></ToggleEnable>
			<Port PortID="11">
				<OfferedEffect Effect="Data" Operator="=" Attribute="true"></OfferedEffect>
			</Port>
			<Port PortID="12">
				<OfferedEffect Effect="ciphering" Operator="=" Attribute="true"></OfferedEffect>
			</Port>
		</PlaceHolder>
		<PlaceHolder Name="Retransmission" ID="4">
			<ToggleEnable isToggle="false"></ToggleEnable>
			<Port PortID="5">
				<OfferedEffect Effect="Data" Operator="=" Attribute="true"></OfferedEffect>
			</Port>
			<Port PortID="8">
				<OfferedEffect Effect="LossRatio" Operator="=" Attribute="0"></OfferedEffect>
			</Port>
		</PlaceHolder>
		<PlaceHolder Name="msgcount" ID="7">
			<ToggleEnable isToggle="false"></ToggleEnable>
			<Port PortID="13">
				<OfferedEffect Effect="MessageCount" Operator="=" Attribute="true"></OfferedEffect>
			</Port>
			<Port PortID="14">
				<OfferedEffect Effect="Data" Operator="=" Attribute="true"></OfferedEffect>
			</Port>
		</PlaceHolder>
		<PlaceHolder Name="net" ID="6">
			<ToggleEnable isToggle="false"></ToggleEnable>
			<Port PortID="7">
				<OfferedEffect Effect="net" Operator="=" Attribute="true"/>
			</Port>
		</PlaceHolder>
	</Placeholders>
	<Connections>	
		<Connection>			
			<Port PortID="6" Placeholder="app"/>
			<Port PortID="9" Placeholder="Compression"></Port>
		</Connection>
		<Connection>			
			<Port PortID="2" Placeholder="Compression"/>
			<Port PortID="11" Placeholder="Encryption"></Port>
		</Connection>
		<Connection>			
			<Port PortID="12" Placeholder="Encryption"/>
			<Port PortID="5" Placeholder="Retransmission"></Port>
		</Connection>
		<Connection>			
			<Port PortID="13" Placeholder="msgcount"/>
			<Port PortID="5" Placeholder="Retransmission"></Port>
		</Connection>
		<Connection>			
			<Port PortID="14" Placeholder="msgcount"/>
			<Port PortID="6" Placeholder="app"></Port>
		</Connection>
		<Connection>			
			<Port PortID="8" Placeholder="Retransmission"/>
			<Port PortID="7" Placeholder="net"></Port>
		</Connection>
	</Connections>
	<CoveredEffects>	
		<CoveredEffect Effect="retransmission" Operator="=" Attribute=" true" isToggle="false"/>	
		<CoveredEffect Effect="ciphering" Operator="=" Attribute=" true" isToggle="false"/>
		<CoveredEffect Effect="DataReduction" Operator="=" Attribute=" true" isToggle="false"/>
		<CoveredEffect Effect="MessageCount" Operator="=" Attribute=" true" isToggle="false"/>
	</CoveredEffects>
</Template>
