=== abbas-siddiqui/Template_Based_Composition/Demo_With_GUI/Template_Demo/xml-resources/jaxb/Network_Description/Offerings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 rel. 2 (x64) (http://www.altova.com) by Markus Hillenbrand (University of Kaiserslautern) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Offerings">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Mandatory" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Offering" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Effect" type="xs:token"/>
										<xs:element name="Operator" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="="/>
													<xs:enumeration value="=&gt;"/>
													<xs:enumeration value="=&lt;"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Attribute" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:token">
														<xs:attribute name="Unit" type="xs:string" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="Weight" type="xs:token" default="0" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Optional" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Offering" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Effect" type="xs:token"/>
										<xs:element name="Operator" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="="/>
													<xs:enumeration value="=&gt;"/>
													<xs:enumeration value="=&lt;"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Attribute" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:token">
														<xs:attribute name="Unit" type="xs:string" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="Weight" type="xs:token" default="0" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== abbas-siddiqui/Template_Based_Composition/Demo_With_GUI/Template_Demo/Extra_Files/NetwokParameters/Network1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Offerings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file://SHADOW/khondoker/workspace/AppParsingUpdated2/xml/Offerings.xsd">
	<Optional>
		<Offering>
			<Effect>throughput</Effect>
			<Operator>=</Operator>
			<Attribute>3</Attribute>
		</Offering>
		<Offering>
			<Effect>delay</Effect>
			<Operator>=</Operator>
			<Attribute>100</Attribute>
		</Offering>
		<Offering>
			<Effect>keystrength</Effect>
			<Operator>=</Operator>
			<Attribute>0</Attribute>
		</Offering>	
		<Offering>
			<Effect>lossratio</Effect>
			<Operator>=</Operator>
			<Attribute>0.5</Attribute>
		</Offering>
		<Offering>
			<Effect>bandwidth</Effect>
			<Operator>=</Operator>
			<Attribute>4</Attribute>
		</Offering>
	</Optional>
</Offerings>

=== abbas-siddiqui/Template_Based_Composition/Demo_With_GUI/Template_Demo/Extra_Files/NetwokParameters/Scenario1_Server2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Offerings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file://SHADOW/khondoker/workspace/AppParsingUpdated2/xml/Offerings.xsd">
	<Optional>		
		<Offering>
			<Effect>delay</Effect>
			<Operator>=</Operator>
			<Attribute>10</Attribute>
		</Offering>
		<Offering>
			<Effect>imagequality</Effect>
			<Operator>=</Operator>
			<Attribute>0</Attribute>
		</Offering>
		<Offering>
			<Effect>bandwidth</Effect>
			<Operator>=</Operator>
			<Attribute>1</Attribute>
		</Offering>			
		<Offering>
			<Effect>lossratio</Effect>
			<Operator>=</Operator>
			<Attribute>0</Attribute>
		</Offering>		
	</Optional>
</Offerings>
