=== abbas-siddiqui/Template_Based_Composition/Template_Demo/Extra_Files/Descriptions/BB_Description.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 rel. 2 sp1 (x64) (http://www.altova.com) by Markus Hillenbrand (University of Kaiserslautern) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="BuildingBlock">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Port" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="Offering">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Effect" type="xs:token"/>
										<xs:element name="Operator" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:token">
													<xs:enumeration value="=&lt;"/>
													<xs:enumeration value="=&gt;"/>
													<xs:enumeration value="="/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Attribute" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Formula" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:token">
																	<xs:attribute name="Type" type="xs:string" use="required"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="Unit" type="xs:string" use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Requirement" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Effect" type="xs:token"/>
										<xs:element name="Operator" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:token">
													<xs:enumeration value="=&lt;"/>
													<xs:enumeration value="=&gt;"/>
													<xs:enumeration value="="/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Attribute" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Formula" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:token">
																	<xs:attribute name="Type" type="xs:string" use="required"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="Unit" type="xs:string" use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="PortID" type="xs:ID" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Optional" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="QOS" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Effect" type="xs:token"/>
										<xs:element name="Operator" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:token">
													<xs:enumeration value="="/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Attribute" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Formula" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:token">
																	<xs:attribute name="Type" type="xs:string" use="required"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="Unit" type="xs:string" use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="UUID"/>
			<xs:attribute name="BBID" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== abbas-siddiqui/Template_Based_Composition/Demo_With_GUI/Template_Demo/Extra_Files/BBPool/ImageComp75.xml
<?xml version="1.0" encoding="UTF-8"?>
<BuildingBlock BBID="ImageComp75" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file://SHADOW/siddiqui/Project_Work/Berlin_Status_Meeting_2012/TemplateBasedApproach/Prototyp_Implemenation/Versions/Template_Demo/Extra_Files/Descriptions/BB_Description.xsd">      
		<Port PortID="down">			
			<Offering>
				<Effect>DataReduction</Effect>
				<Operator>=</Operator>
				<Attribute Unit="ms"><Formula Type="value">true</Formula></Attribute>
			</Offering>
		</Port>	
		<Port PortID="up">			
			<Offering>
				<Effect>Data</Effect>
				<Operator>=</Operator>
				<Attribute Unit=""><Formula Type="value">true</Formula></Attribute>
			</Offering>
		</Port>		
		<Optional>
		<QOS>
			<Effect>delay</Effect>
			<Operator>=</Operator>
			<Attribute Unit="ms"><Formula Type="value">75</Formula></Attribute>
		</QOS>
		<QOS>
			<Effect>imagequality</Effect>
			<Operator>=</Operator>
			<Attribute Unit="ms"><Formula Type="value">75</Formula></Attribute>
		</QOS>
		<QOS>
			<Effect>bandwidth</Effect>
			<Operator>=</Operator>
			<Attribute Unit="bits"><Formula Type="value">0</Formula></Attribute>
		</QOS>
		<QOS>
			<Effect>lossratio</Effect>
			<Operator>=</Operator>
			<Attribute Unit="%"><Formula Type="value">0</Formula></Attribute>
		</QOS>		
		</Optional>
</BuildingBlock>

=== abbas-siddiqui/Template_Based_Composition/Template_Demo/Extra_Files/BBPool/app.xml
<?xml version="1.0" encoding="UTF-8"?>
<BuildingBlock BBID="app" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file://SHADOW/siddiqui/Project_Work/Berlin_Status_Meeting_2012/TemplateBasedApproach/Prototyp_Implemenation/Versions/Template_Demo/Extra_Files/Descriptions/BB_Description.xsd">      
		<Port PortID="data">			
			<Offering>
				<Effect>application</Effect>
				<Operator>=</Operator>
				<Attribute Unit=""><Formula Type="value">true</Formula></Attribute>
			</Offering>
		</Port>			
		<Optional>
		<QOS>
			<Effect>processingdelay</Effect>
			<Operator>=</Operator>
			<Attribute Unit="ms"><Formula Type="value">0</Formula></Attribute>
		</QOS>
		<QOS>
			<Effect>throughput</Effect>
			<Operator>=</Operator>
			<Attribute Unit="ms"><Formula Type="value">0</Formula></Attribute>
		</QOS>
		<QOS>
			<Effect>keystrength</Effect>
			<Operator>=</Operator>
			<Attribute Unit="bits"><Formula Type="value">0</Formula></Attribute>
		</QOS>
		<QOS>
			<Effect>lossratio</Effect>
			<Operator>=</Operator>
			<Attribute Unit="%"><Formula Type="value">0</Formula></Attribute>
		</QOS>			
		</Optional>
</BuildingBlock>
